module.exports = {
  name: 'cinnamon',
  description: 'Cinnamon self introduction!',
  execute (client, message, args) {
    message.channel.send('https://youtu.be/ccIkbzFxwjc')
    message.channel.send('Cinnamon (シナモン Shinamon) is a relaxed, constantly-grinning laid-back catgirl. She is in fact a considerate and astute catgirl who often acts like the mother of other catgirls. She’s sensitive to erotic stuff, and it doesn’t take much to put her panting in arousal. Her company demands others’ patience in the face of her occasional masochistic fantasies. She’s also the most confident one in terms of bust size among the catgirls.')
    message.channel.send('**Appearance**')
    message.channel.send('Cinnamon has periwinkle hair which is usually tied up into a high ponytail with a teal ribbon, which comes to about neck length, and when let down can reach past shoulder length. As a Scottish Fold, Cinnamon ears naturally fold downwards rather than point up, and both her ears and her tail are the same color as her hair. She has amber eyes, and her silver bell is hung from a pink choker around her neck. She has the biggest bust in all the Minaduki catgirls.')
    message.channel.send('Cinnamon casual attire consists of a light blue and white magical girl dress complemented by matching knee-length white socks and pair of gloves with light purple frills on the hems. She wears pink shoes with matching ribbons on her chest and on her tail.')
    message.channel.send('**Personality**')
    message.channel.send('Cinnamon is among the most easygoing of the Minaduki catgirls. She is soft-spoken, polite, and cheerful. However as a kitten, Cinnamon was extremely shy to the point of hiding in the corner of her room and not speaking to anyone else, until Maple forcibly coerces her out of her shell. It is due to this that of all the Minaduki catgirls, Cinnamon is the closest to Maple.')
    message.channel.send('Though she is often cheerful, Cinnamon at times has expressed hints of a low self esteem, forwardly offering herself as a catpanion to Kashou and settling for being the "least loved" of them all, and mentioning that her only redeeming feature were her big breasts while bra shopping. Despite this, Cinnamon loyalty to Maple has shown her to be very selfless, fully supporting her dream of becoming a singer to the point of resorting to self-sacrifice, by taking on Maple workloads at La Soleil, to see it come to fruition.')
    message.channel.send('Cinnamon fatal flaw is that she regularly goes into "drooling" episodes; moments where she becomes aroused, usually over the mundane. During these episodes she shows signs of being a masochist, expressing joy at being scolded by Kashou and being tied up with rope while on stage, and at times a sadist, teasing Kashou while bra shopping with her. She seems rather shameless about these episodes and they can occur at any time, including in public or in front of customers while working at La Soleil.')
    message.channel.send('**Attributes**')
    message.channel.send('Race : Catgirl')
    message.channel.send('Breed : Scottish Fold')
    message.channel.send('Gender : Female')
    message.channel.send('Age : 2 years old')
    message.channel.send('**Characteristics**')
    message.channel.send('Complexion : Pale')
    message.channel.send('Height(Kid) : 150cm')
    message.channel.send('Weight(Kid) : 45.3kg')
    message.channel.send('3 Size(Kid) : 87cm,56cm,83cm')
    message.channel.send('Hair Colour : Periwinkle (Lavender blue)')
    message.channel.send('Eye Colour : Amber')
    message.channel.send('Occupation : La Soleil employee')
    message.channel.send('**Relationships**')
    message.channel.send('Azuki - Older Sister')
    message.channel.send('Maple - Older Sister')
    message.channel.send('Coconut - Younger Sister')
    message.channel.send('Chocola - Younger Sister')
    message.channel.send('Vanilla - Younger Sister')
    message.channel.send('Shigure - Owner')
    message.channel.send('Kashou - Owner and Partner')
    message.channel.send('**Trivia**')
    message.channel.send('Cinnamon is one of three of the Minaduki catgirls whos hair color does not match the food item they are name after, with her hair color being violet, rather than being brown, the color of cinnamon.')
    message.channel.send('*The others being Azuki, who has brown hair, when Adzuki beans have a red color, and Coconut having beige colored hair, instead of the brown color Coconuts have.*')
    message.channel.send('https://static.wikia.nocookie.net/nekopara/images/1/1e/Ch_cin_img_01.png/revision/latest/scale-to-width-down/305?cb=20200519141059')
  }
}
