module.exports = {
  name: 'coconut',
  description: 'Coconut self introduction!',
  execute (client, message, args) {
    message.channel.send('https://youtu.be/isJEI88_ZgI')
    message.channel.send('Coconut (ココナツ Kokonatsu) is a tall, cool-and-collected, glamorous catgirl. Despite her stature, she’s actually the third youngest of the Minaduki catgirls. She has a mild complex about having a not-quite-feminine appearance. However, her loyalty to her master Shigure is greater than any dog’s and she has extraordinary physical capabilities. Although she loves helping people, it almost always ends up failing due to her poor coordination skills.')
    message.channel.send('**Appearance**')
    message.channel.send('Coconut is the tallest of the Minaduki sisters as well as the most developed for her age, sporting the second largest bust size of the Minaduki catgirls, second only to Cinnamon; this is in stark contrast to Azuki who is the oldest but looks the youngest. She has white hair with light blonde tips which reaches down to the bottom of her waist, and a matching bushy tail. She has heterochromic eyes which gives her two different eye colours; blue and amber.')
    message.channel.send('Her casual attire consists of a pink midriff-baring shoulder-less crop top, denim hot pants with what appears to be a purple thong pulled up to be partially visible across her hips above her shorts, and purple heeled shoes. Her silver bell is hung from a purple choker around her neck.')
    message.channel.send('**Personality**')
    message.channel.send('As one of the younger Minaduki catgirls, Coconut is among the more emotional of them. Contrary to her outward appearence, she expresses a strong desire to be considered cute, rather than be known for her physical strength. As a Maine Coon kitten she has rapidly developed an adult body which she is self-conscious about; her rapid physical development is what triggered her desire to mature as quickly as possible so as not to be a burden to Kashou or her sisters, and develops a "mature" façade to compensate. This however backfires, and causes her to overwhelm herself and become extremely clumsy. Her repeated clumsiness then causes her to develop a low self-esteem and frequently fall into extreme bouts of self-deprecation.')
    message.channel.send('After becoming Kashou catpanion, she accepts herself for who she is and embraces her physical strength. She becomes more playful and energetic, less prone to clumsiness, and no longer heavily attacks herself when she messes up.')
    message.channel.send('Coconut, like Vanilla, demonstrates the ability to see through Azuki tsundere facade, at times forcing her to become more honest than she lets on.')
    message.channel.send('**Attributes**')
    message.channel.send('Race : Catgirl')
    message.channel.send('Breed : Maine Coon')
    message.channel.send('Gender : Female')
    message.channel.send('Age : 1 year')
    message.channel.send('**Characteristics**')
    message.channel.send('Complexion : Tan')
    message.channel.send('Height(Kid) : 137cm')
    message.channel.send('Height(Adult) : 168cm')
    message.channel.send('Weight(Kid) : 31.8kg')
    message.channel.send('3 Size(Kid) : 68cm,52cm,70cm')
    message.channel.send('3 Size(Adult) : 93cm,61cm,89cm')
    message.channel.send('Hair Colour : Light Blond')
    message.channel.send('Eye Colour : Amber/Blue')
    message.channel.send('Occupation : La Soleil employee')
    message.channel.send('**Relationships**')
    message.channel.send('Azuki - Older Sister')
    message.channel.send('Maple - Older Sister')
    message.channel.send('Cinammon - Older Sister')
    message.channel.send('Chocola - Younger Sister')
    message.channel.send('Vanilla - Younger Sister')
    message.channel.send('Shigure - Owner')
    message.channel.send('Kashou - Owner and Partner')
    message.channel.send('**Trivia**')
    message.channel.send('Contrary to Coconut desire to be considered cute, her standard attire is more seductive than cute.')
    message.channel.send('Coconut is a big eater. As stated by Vanilla: "Much more than the usual catgirl".')
    message.channel.send('https://static.wikia.nocookie.net/nekopara/images/a/a0/Ch_coc_img_01.png/revision/latest/scale-to-width-down/310?cb=20150511104510')
  }
}
