module.exports = {
  name: 'maple',
  description: 'Maple self introduction!',
  execute (client, message, args) {
    message.channel.send('https://youtu.be/qVmrIZTE06U')
    message.channel.send('Maple (メイプル Meipuru) is a prideful, quick-thinking, and often arrogant catgirl. She loves the latest brand-name products and purrs only when she wants something from Shigure. She typically speaks frankly, yet remains attentive to those around her. She is, as the saying goes, a scaredy-cat, always turning on every light on the way to the bathroom at night. Out of all the catgirls, her tongue is the most sensitive to hot things.')
    message.channel.send('**Appearance**')
    message.channel.send('Maple has orange, back-length wavy hair and her eyes are dark green. True to her breed as an American Curl, she has curled ears, and a matching fluffy tail.')
    message.channel.send('She receives a silver colored Bell although it is not mentioned what corresponding rank or status comes with the color a catgirl obtains after taking her bell exam')
    message.channel.send('**Personality**')
    message.channel.send('Maple is presented as the most independent and mature of the Minaduki catgirls, showing herself off as being refined yet at times haughty. She is extremely prideful, although her pride has at times been her downfall, as shown when buying her first guitar with Kashou which required his intervention to rescue her from herself.')
    message.channel.send('Maple appears to be more self aware and more ambitious than the other catgirls. In Vol 3 she reveals that she aspires to be a singer, although her own lack of self confidence holds her back. She has a particular dislike for the term "catgirl", since she felt people who refer to her as one didnt view her as an individual, but rather as just a catgirl.')
    message.channel.send('She is extremely scared of the dark, a fact which she hates being brought up by the other catgirls.')
    message.channel.send('**Attributes**')
    message.channel.send('Race : Catgirl')
    message.channel.send('Breed : American Curl')
    message.channel.send('Gender : Female')
    message.channel.send('Personality : Independent, classy, and calm')
    message.channel.send('Age : 2 years')
    message.channel.send('**Appearance**')
    message.channel.send('Outfit : School Uniform')
    message.channel.send('**Characteristics**')
    message.channel.send('Complexion : Pale')
    message.channel.send('Height(Kid) : 157cm')
    message.channel.send('Weight(Kid) : 51.7kg')
    message.channel.send('3 Size(Kid) : 81cm,57cm,84cm')
    message.channel.send('Hair Colour : Blonde')
    message.channel.send('Eye Colour : Green')
    message.channel.send('Occupation : La Soleil employee')
    message.channel.send('**Relationships**')
    message.channel.send('Azuki - Older Sister')
    message.channel.send('Cinnamon - Younger Sister')
    message.channel.send('Coconut - Younger Sister')
    message.channel.send('Chocola - Younger Sister')
    message.channel.send('Vanilla - Younger Sister')
    message.channel.send('Shigure - Owner')
    message.channel.send('Kashou - Owner and Partner')
    message.channel.send('**Trivia**')
    message.channel.send('Maple is the only catgirl to not have her clothes be picked by Shigure; this implies that Maple is the only catgirl independent enough to be trusted with her own fashion sense.')
    message.channel.send('Maple appears to be the only known neko that has the knowledge to use technology, evidenced in Nekopara Vol. 1 as she was "teaching" Chocola about emoticons and LIME stamps on her phone.')
    message.channel.send('In the past, Maple used to strip down completely whenever she is using the bathroom. Maple claims that she can go to the bathroom "only half-naked" now.')
    message.channel.send('*Maple also, apparently, leaves the bathroom door completely open while inside. This is was revealed to be due to Azuki "traumatizing" her, by locking her in the bathroom.*')
    message.channel.send('In Nekopara Vol. 2, at some point when you touch Maple upper sensitive parts, she sings the first four notes of Beethoven Symphony No. 5.')
    message.channel.send('While the make of Maple guitar is notpe mentioned, it is aparance closely resembles a slightly modified Fender Paramount PM-1 Deluxe Dreadnought VS.')
    message.channel.send('**Extra**')
    message.channel.send('In Nekopara Vol. 3, Maple singing My Grandfather Clock in concert, below is the link about the song.')
    message.channel.send('https://youtu.be/guJWro5LuhU')
    message.channel.send('In nekopara anime episede 9, Maple also sing a song. Check the link below to listen the song.')
    message.channel.send('https://youtu.be/NfPx0XSo61Y')
    message.channel.send('https://static.wikia.nocookie.net/nekopara/images/b/b8/Ch_map_img_01.png/revision/latest/scale-to-width-down/250?cb=20150511103909')
  }
}
