module.exports = {
  name: 'milk',
  description: 'Milk self introduction!',
  execute (client, message, args) {
    message.channel.send('http://pm1.narvii.com/6159/4d34d4d66940d1d1908d6ad122d3968b9951f612_00.jpg')
    message.channel.send('Milk (ミルク Miruku) also known as Food Stand Cat, is a minor character introduced in Nekopara Vol. 1. She manages a takoyaki food stand in a park where Kashou, Chocola and Vanilla often used to walk at on days like that day. Milk is owned by an unnamed female who formally owns the takoyaki stand Milk runs for her.')
    message.channel.send('**Appearance**')
    message.channel.send('Milk has greyish blue hair and possesses olive drab eyes. She wears an employee uniform that consists of what appears to be a brown apron that has a yellow collar. She also wears an inside white skirt or t-shirt (Her full outfit cannot be seen; thus all of these are just speculations).')
    message.channel.send('**Personality**')
    message.channel.send('Milk is very cheerful and lively. She will likely approach anyone without hesitation and offer them to eat at her owner takoyaki shop. She also is very polite towards her elders as she addressed Chocola, Vanilla, and Coconut as "older sisters". In addition, she is very sociable as she is able to mingle with other catgirls with ease.')
    message.channel.send('**Attributes**')
    message.channel.send('Race : Catgirl')
    message.channel.send('Breed : Unknown')
    message.channel.send('Gender : Female')
    message.channel.send('Personality : Very lively and sociable')
    message.channel.send('Age : 7 months')
    message.channel.send('**Appearance**')
    message.channel.send('Outfit : Uniform')
    message.channel.send('**Characteristics**')
    message.channel.send('Complexion : Pale')
    message.channel.send('Hair Colour : Grayish Blue')
    message.channel.send('Eye Colour : Olive Drab')
    message.channel.send('Occupation : Takoyaki Vendor')
    message.channel.send('**Relationships**')
    message.channel.send('Coconut - Savior')
    message.channel.send('Chocola - Acquiantance')
    message.channel.send('Vanilla - Acquiantance')
    message.channel.send('Kashou - Acquiantance')
    message.channel.send('Takoyaki Stand Owner - Owner/Master')
    message.channel.send('**Trivia**')
    message.channel.send('Prior to Nekopara Vol. 2, Milk name wasnt revealed. Instead, she was given the name Takoyaki Catgirl. In the English version, she is known as Food Stand Cat.')
    message.channel.send('Milk was also a stray like Chocola and Vanilla.')
    message.channel.send('Milk and Shigure share the same voice actor.')
    message.channel.send('When you access the backlog in Nekopara Vol. 2 and before she introduces herself to Coconut, her name was already revealed.')
    message.channel.send('https://static.wikia.nocookie.net/nekopara/images/f/fb/Milk_vol_4.jpg/revision/latest/top-crop/width/450/height/450?cb=20200723224217')
  }
}
