module.exports = {
  name: 'azuki',
  description: 'Azuki self introduction!',
  execute (client, message, args) {
    message.channel.send('https://youtu.be/yH4R0MwExvo')
    message.channel.send('Azuki (アズキ Azuki) is the eldest of the Minaduki catgirls. She is fearless and easygoing. Azuki never hides her nature. She’s not afraid to voice her mind, often with a few uncouth words. Most tasks are a nuisance to her at best, leaving her with little motivation to do anything. She is actually quite capable, though, and can do almost anything if put to work (aside from physical labor). She has a complex about her body size, however. Never, ever mention “short legs” around her.')
    message.channel.send('**Appearance**')
    message.channel.send('Contrary to her age, Azuki is the second shortest of the Minaduki catgirls as well as the most youthful in appearence due to her Munchkin traits; this is in stark contrast to Coconut who is the third youngest, but appears to be one of the oldest. She has brown neck-length hair tied up by two cat-themed hair clips into small twin tails on the opposite sites of her head. She has brown eyes, and a striped tail.')
    message.channel.send('Her casual attire consists of a Sailor suit-style white sleeveless buttoned shirt with blue collar and a red ascot. She wears a blue pleated skirt, and black Mary Jane shoes with white ankle socks. Her gold bell is hung from a red choker around her neck.')
    message.channel.send('**Personality**')
    message.channel.send('Azuki is one of the most responsible of the Minaduki catgirls, often acting as their supervisor when helping to run La Soleil. However her brash personality often sees her come to blows with her sisters, in particular Coconut. Deep down however, she cares about her family and their well-being, and checks on them even if she previously had a fight with them.')
    message.channel.send('Azuki fatal flaw is that she has trouble expressing her emotions or desires, which she hides behind her tsundere façade. Both Coconut and Vanilla have demonstrated the ability to see through this trait, at times forcing her to become honest with herself.')
    message.channel.send('After becoming Kashou catpanion, she actively attempts to become more honest, this in turn causes her to get into less fights with her sisters.')
    message.channel.send('**Attributes**')
    message.channel.send('Race : Catgirl')
    message.channel.send('Breed : Munchkin Cat')
    message.channel.send('Gender : Female')
    message.channel.send('Age : 3 years')
    message.channel.send('**Characteristics**')
    message.channel.send('Complexion : Pale')
    message.channel.send('Height(Kid) : 142cm')
    message.channel.send('Weight(Kid) : 35.1kg')
    message.channel.send('3 Size(Kid) : 69cm,50cm,72cm')
    message.channel.send('Hair Colour : Brown')
    message.channel.send('Eye Colour : Brown')
    message.channel.send('Occupation : La Soleil employee')
    message.channel.send('**Relationships**')
    message.channel.send('Maple - Younger Sister')
    message.channel.send('Cinnamon - Younger Sister')
    message.channel.send('Coconut - Younger Sister')
    message.channel.send('Chocola - Younger Sister')
    message.channel.send('Vanilla - Younger Sister')
    message.channel.send('Shigure - Owner')
    message.channel.send('Kashou - Owner and Partner')
    message.channel.send('**Trivia**')
    message.channel.send('Azuki name is a transliteration of Adzuki beans, a type of small edible beans from eastern Asia. Her tail also sports similar colors to the brown variety of Adzuki beans.')
    message.channel.send('Azuki refers to the other catgirls by reordering/combining/shortening their names. She refers to Cinnamon as "Mon-Cinna", Maple as "Pull-May", Chocola and Vanilla as "ChocoVani", and lastly Coconut as "Nuts".')
    message.channel.send('Azuki is the first of Kashou catpanions to consistently call him by name, as Chocola and Vanilla refer to him as "Master" and Coconut preferring to call Kashou "Onii-chan".')
    message.channel.send('Azuki has been shown to be easily manipulated by food, with Shigure being known to punish her by withholding snacks from her, Azuki meanwhile, sees this as "torture".')
    message.channel.send('Azuki is one of three of the Minaduki catgirls who hair color does not match the food item they are name after, having brown hair, while Adzuki beans being a red color.')
    message.channel.send('*The others being Cinnamon having violet colored hair, rather than being brown, as cinnamon commonly is, and Cacao being mint, instead of the orange-like color Cacao seeds have.*')
    message.channel.send('https://static.wikia.nocookie.net/nekopara/images/5/51/Ch_azu_img_01.png/revision/latest/scale-to-width-down/228?cb=20200519140801')
  }
}
